name: sushil-compose

services:
  inventory-service:
    build:
      context: ../inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "8082:8082"
    environment:
      ESPRESSO_SHOT_QUANTITY: 5
      MILK_QUANTITY: 10
      HOT_WATER_QUANTITY: 20
      MILK_FOAM_QUANTITY: 15
      INVENTORY_URL: http://inventory-service:8082
    networks:
      - app-network

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8083:8080"
    depends_on:
      - inventory-service
    environment:
      INVENTORY_URL: http://inventory-service:8082
    networks:
      - app-network

networks:
  app-network:
    driver: bridge